Removendo $charset
cassiohalmeida/laravel-pagsegurotransparente pull request #6
Opened 2020-08-24 04:40 UTC by thiagobueno

O $charset vem sempre nulo e com isso da erro na resposta do pagSeguro, colocando o charset=ISO-8859-1 direto resolve o problema.

2020-08-27 15:31 UTC, cassiohalmeida commented
Olá @thiagobueno 
Obrigado pelo PR.
Você poderia, por favor, descrever exatamente o erro que você está tendo? O `charset` é o último parâmetro desse método e tem o valor default `ISO-88859-1`.
Provavelmente o problema está nos métodos `post` e `get`. Que também possuem o `charset` default, porém com o valor padrão `null`.
Poderia fazer esse update nos métodos e dizer se isso resolve o problema?
Valeu!

2020-08-27 15:32 UTC, cassiohalmeida requested changes
Verifique meu comentário.

2020-08-27 15:42 UTC, thiagobueno commented
Opa @cassiohalmeida 

`var_dump(PagSeguro::printSessionId());`

O resultado é esse:
`Class 'Cassioalmeida\Pagsegurotransparente\Exception' not found`

Ai fiz outro teste, um var_dump dentro do metodo **printSessionId** 

`$httpConnection = new HttpConnection();
  $httpConnection->post($this->pagSeguroData->getSessionURL(), $this->pagSeguroData->getCredentials());
  var_dump($httpConnection);`

O resultado:

```
{
"timestamp":"2020-08-27T15:40:49.710+0000",
"status":415,
"error":"Unsupported Media Type",
"message":"Invalid mime type \"application/x-www-form-urlencoded; charset=\": 'value' must not be empty",
"path":"/v2/sessions"
}
```

Ai por isso passei o valor ISO-88859-1 direto e não pela variavel

2020-08-27 16:04 UTC, thiagobueno commented
Esqueci de mencionar que o problema da em modo de produção em sandbox não da esse erro.

2020-10-09 01:01 UTC, cassiohalmeida commented
@thiagobueno Desculpe a demora, essas últimas semanas não foram fáceis.

Seguinte, gostaria de te pedir para validar uma ideia. 
Acredito que não devemos remover o `$charset` como parâmetro do método `curlConnection`. Isso pode quebrar quem precisa passar outro valor ali.
Porém, os únicos métodos que chamam o `curlConnection` (pois ele é privado) dentro da classe `HttpConnection` são o `get` e o `post`.
Esses métodos também possuem o 4 parâmetro como `charset`, porém como `null`. Podemos então definir nesses métodos o valor default, por exemplo:

```
public function post($url, array $data = null, $timeout = null, $charset = 'ISO-8859-1') {
        return $this->curlConnection('POST', $url, $data, $timeout, $charset);
    }
```
```
public function get($url, array $data = null, $timeout = null, $charset = 'ISO-8859-1') {
        return $this->curlConnection('GET', $url, $data, $timeout, $charset);
    }
```
Veja se isso resolve o problema. E se sim, poderia atualizar a PR para podermos mergear?

Valeu!

2020-10-16 00:42 UTC, thiagobueno reviewed
Atualizado os metodos post e get

2020-10-17 11:00 UTC, cassiohalmeida approved these changes

2020-10-17 14:05 UTC, merged

2020-10-17 14:44 UTC, cassiohalmeida commented
PR mergeada. Obrigado pela ajuda @thiagobueno